type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
}

type Project @table {
  name: String!
  description: String
  status: String!
  dueDate: Date
  createdAt: Timestamp!
  updatedAt: Timestamp!
  owner: User!
}

type Task @table {
  title: String!
  description: String
  status: String!
  dueDate: Date
  priority: String
  createdAt: Timestamp!
  updatedAt: Timestamp!
  project: Project!
  assignee: User
}

type Comment @table {
  content: String!
  createdAt: Timestamp!
  task: Task!
  author: User!
}

type ProjectMembership @table(key: ["project", "user"]) {
  project: Project!
  user: User!
  role: String!
  createdAt: Timestamp!
}